### PR TITLE
fully automated pimox7 installaton on a RPi4 B

### PR DESCRIPTION
**Pull request by TuxfeatMac**
Maybe you can ad it manualy I've messed up my commits... somehow =D

### CODE REVIEW

**Comment by TuxfeatMac** [comment]
will recreate...

**Comment by aanon4** [comment]
Nice, but I think it needs to do a couple of extra things:

1. Request the hostname and IP address rather than hardwiring it. At least force them to edit the file with their specific values.
2. Warn the user in big letter and have them actively agree before overwriting various files. Best tell them which files will be overwritten too.

**Comment by vonloschz** [comment]
use DietPi with DietPi-Automation https://dietpi.com/phpbb/viewtopic.php?t=273
and vote for pimox7 integration https://dietpi.com/phpbb/viewtopic.php?f=12&t=9373

**Comment by TuxfeatMac** [comment]
I've allso written a full automated installation script with DietPi-Automation, anyone intrested ? Maybe create another pull request ?

**Pull request closed without merging**
